### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by AdonisPhusis29** [PIVX-Project/PIVX-SPMT#39]
Thank you very much for this V5 I wanted to say thank you I see a lot of beautiful things and a lot of passion. I can't even find the word and I'm sure I rate you gross ... and thanks again and best wishes! 

Oh yes I can no longer take out my reward from SPMT too lol

![](https://cdn.discordapp.com/attachments/377493778207866890/797236476118040651/unknown.png)

**Comment by random-zebra** [comment]
Hey Adonis! thanks for your kind words.

This issue is happening because the backend is running 5.0 (which modified the RPC input of `sendrawtransaction`).

The fix for SPMT is already merged (<https://github.com/PIVX-Project/PIVX-SPMT/commit/f99674885bd7471965d0ac09f347ea23445f99a7>) but new binaries haven't been released yet.

So, currently, your options are:
1) run the current SPMT version with a backend client **not** updated to PIVX v5.0 yet (e.g. the remote server `losangeles` is still running v4.3.0).
2) run SPMT from the sources, or compile the binaries yourself.
3) wait for the release

Note: You don't strictly need SPMT to move your masternode rewards without touching the collateral, since Ledger Live now offers coin-control (https://support.ledger.com/hc/en-us/articles/360015996580-Using-Coin-control), you can directly spend from there.

**Comment by tbearma1** [comment]
Hallo Zebra :-)
Great job!
i upgradet my masternode (VPN CentOS) and my wallet (on macbook) to 5.0.1
now i cloned your projects SPTM and PET4L and run them from sources on my macbook.
It was possible for me to send the masternode reward AND the cold-staking reward from my hw-wallet to a pivx controller. from the pivx-controller (pivx softwarewallet) i did a delegation back to the hw-wallet-owneraddress.
Everything is working very well.
Thanks a lot and have a good evening

**Comment by random-zebra** [comment]
Thanks for the feedback @tbearma1 :pray:

**Comment by random-zebra** [comment]
Fixed in `0.6.2`. Closing.
